version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fortnite_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fortnite_auth
    ports:
      - "5432:5432" # Прокидываем порт наружу, чтобы go run локально мог подключиться
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fortnite_redis
    ports:
      - "6379:6379" # Прокидываем порт наружу

volumes:
  postgres_data: